version: '3'
tasks:
  format:
    - |
      echo -e "Formatting..."
      npm run format
      echo -e "\nLinting...\n"
      npm run lint:fix
      echo -e "\nFormatting Database...\n"
      npm run db:push
      npm run db:format
  pre-commit:
    - |
      pre-commit clean
      pre-commit install --hook-type commit-msg --hook-type pre-push --hook-type pre-commit
      pre-commit run --all-files
